services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    working_dir: /app
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    working_dir: /app
