GET http://localhost:8000/ping

###
GET http://localhost:8000/event/1

###
POST http://localhost:8000/list_events
Content-Type: application/json

{
    "station": "ELYSE"
}

###
GET http://localhost:8000/user_event/1


###
POST http://localhost:8000/list_user_events
Content-Type: application/json

{
    "station": "ELYSE"
}
